/*Not So Common Operator*/
public enum NSCO {
    SHIFT, BIT_AND, BIT_OR, CARET,
    ONE_ADD_SUB, ADD_ASSIGN, SUB_ASSIGN, MULT_ASSIGN, DIV_ASSIGN,
    AND_ASSIGN, OR_ASSIGN, XOR_ASSIGN, RSHIFT_ASSIGN, URSHIFT_ASSIGN, LSHIFT_ASSIGN, MOD_ASSIGN
}

/*
*
* ONE_ADD_SUB -> ++ or --
* ADD_ASSIGN ->  +=
* SUB_ASSIGN ->  -=
* MULT_ASSIGN -> *=
* DIV_ASSIGN ->  /=
*/
